---


# Template Config file
- name: REDIS | config | Template redis.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
#    backup: yes
  with_items:
    - src: "redis.conf.j2"
      dest: "{{ redis_running_conf_file }}"