---

- name: MYSQL | Start | Run MySQL Docker container
  community.docker.docker_container:
    name: mysql-server
    image: "{{ mysql_image }}"
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
#      MYSQL_DATABASE: "your_database"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    ports:
        - "{{ mysql_port|int  }}:{{ mysql_port|int  }}"
    volumes:
        - "{{ conf_settings }}"
        - "{{ data_settings }}"